# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            Jeroen van der Tuin
tagline:          'A Developer Blog'
description:      'This blog contains mostly my ramblings about the various technologies that I use in my projects.'
url:              http://www.vandertuin.nl

# About/contact
author:
  name:           'Jeroen van der Tuin'
  url:            https://twitter.com/jeromche

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/jeromche/jeromche.github.io
